# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assetList_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_asset_list_widget(object):
    def setupUi(self, asset_list_widget):
        asset_list_widget.setObjectName("asset_list_widget")
        asset_list_widget.resize(230, 452)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(asset_list_widget.sizePolicy().hasHeightForWidth())
        asset_list_widget.setSizePolicy(sizePolicy)
        asset_list_widget.setMinimumSize(QtCore.QSize(230, 0))
        asset_list_widget.setMaximumSize(QtCore.QSize(230, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(asset_list_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.assets_label = QtWidgets.QLabel(asset_list_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.assets_label.setFont(font)
        self.assets_label.setObjectName("assets_label")
        self.verticalLayout.addWidget(self.assets_label)
        self.search_bar = QtWidgets.QLineEdit(asset_list_widget)
        self.search_bar.setEnabled(False)
        self.search_bar.setObjectName("search_bar")
        self.verticalLayout.addWidget(self.search_bar)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(asset_list_widget)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.asset_tree = QtWidgets.QTreeWidget(asset_list_widget)
        self.asset_tree.setAlternatingRowColors(False)
        self.asset_tree.setIndentation(20)
        self.asset_tree.setRootIsDecorated(True)
        self.asset_tree.setUniformRowHeights(False)
        self.asset_tree.setAnimated(False)
        self.asset_tree.setObjectName("asset_tree")
        self.asset_tree.header().setVisible(False)
        self.asset_tree.header().setCascadingSectionResizes(False)
        self.asset_tree.header().setSortIndicatorShown(False)
        self.asset_tree.header().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.asset_tree)

        self.retranslateUi(asset_list_widget)
        QtCore.QMetaObject.connectSlotsByName(asset_list_widget)

    def retranslateUi(self, asset_list_widget):
        _translate = QtCore.QCoreApplication.translate
        asset_list_widget.setWindowTitle(_translate("asset_list_widget", "Form"))
        self.assets_label.setText(_translate("asset_list_widget", "Assets"))
        self.search_bar.setText(_translate("asset_list_widget", "not available"))
        self.checkBox.setText(_translate("asset_list_widget", "Tag Search (not available)"))
        self.asset_tree.headerItem().setText(0, _translate("asset_list_widget", "1"))
