# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PipelineStepViewer_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pipeline_step_viewer(object):
    def setupUi(self, pipeline_step_viewer):
        pipeline_step_viewer.setObjectName("pipeline_step_viewer")
        pipeline_step_viewer.resize(326, 300)
        self.formLayout = QtWidgets.QFormLayout(pipeline_step_viewer)
        self.formLayout.setObjectName("formLayout")
        self.step_name_label = QtWidgets.QLabel(pipeline_step_viewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_name_label.sizePolicy().hasHeightForWidth())
        self.step_name_label.setSizePolicy(sizePolicy)
        self.step_name_label.setObjectName("step_name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.step_name_label)
        self.step_program_label = QtWidgets.QLabel(pipeline_step_viewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_program_label.sizePolicy().hasHeightForWidth())
        self.step_program_label.setSizePolicy(sizePolicy)
        self.step_program_label.setObjectName("step_program_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.step_program_label)
        self.step_state = QtWidgets.QLabel(pipeline_step_viewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.step_state.sizePolicy().hasHeightForWidth())
        self.step_state.setSizePolicy(sizePolicy)
        self.step_state.setObjectName("step_state")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.step_state)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem)

        self.retranslateUi(pipeline_step_viewer)
        QtCore.QMetaObject.connectSlotsByName(pipeline_step_viewer)

    def retranslateUi(self, pipeline_step_viewer):
        _translate = QtCore.QCoreApplication.translate
        pipeline_step_viewer.setWindowTitle(_translate("pipeline_step_viewer", "Form"))
        self.step_name_label.setText(_translate("pipeline_step_viewer", "Step Name"))
        self.step_program_label.setText(_translate("pipeline_step_viewer", "Program"))
        self.step_state.setText(_translate("pipeline_step_viewer", "State"))
