# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exportWizard_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_export_Wizard(object):
    def setupUi(self, export_Wizard):
        export_Wizard.setObjectName("export_Wizard")
        export_Wizard.resize(758, 367)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(export_Wizard)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.setContentsMargins(-1, 0, -1, -1)
        self.main_layout.setObjectName("main_layout")
        self.asset_list = AssetListView(export_Wizard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asset_list.sizePolicy().hasHeightForWidth())
        self.asset_list.setSizePolicy(sizePolicy)
        self.asset_list.setMinimumSize(QtCore.QSize(230, 0))
        self.asset_list.setObjectName("asset_list")
        self.main_layout.addWidget(self.asset_list)
        self.asset_details_pipeline_layout = QtWidgets.QVBoxLayout()
        self.asset_details_pipeline_layout.setContentsMargins(0, -1, -1, -1)
        self.asset_details_pipeline_layout.setObjectName("asset_details_pipeline_layout")
        self.asset_details = AssetDetailsView(export_Wizard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asset_details.sizePolicy().hasHeightForWidth())
        self.asset_details.setSizePolicy(sizePolicy)
        self.asset_details.setMinimumSize(QtCore.QSize(0, 90))
        self.asset_details.setObjectName("asset_details")
        self.asset_details_pipeline_layout.addWidget(self.asset_details)
        self.pipeline_outputs_layout = QtWidgets.QHBoxLayout()
        self.pipeline_outputs_layout.setContentsMargins(-1, 0, 0, -1)
        self.pipeline_outputs_layout.setObjectName("pipeline_outputs_layout")
        self.pipeline_viewer = PipelineViewerView(export_Wizard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pipeline_viewer.sizePolicy().hasHeightForWidth())
        self.pipeline_viewer.setSizePolicy(sizePolicy)
        self.pipeline_viewer.setObjectName("pipeline_viewer")
        self.pipeline_outputs_layout.addWidget(self.pipeline_viewer)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outputs_label = QtWidgets.QLabel(export_Wizard)
        self.outputs_label.setObjectName("outputs_label")
        self.verticalLayout.addWidget(self.outputs_label)
        self.outputs_list = QtWidgets.QListWidget(export_Wizard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputs_list.sizePolicy().hasHeightForWidth())
        self.outputs_list.setSizePolicy(sizePolicy)
        self.outputs_list.setMaximumSize(QtCore.QSize(100, 16777215))
        self.outputs_list.setObjectName("outputs_list")
        self.verticalLayout.addWidget(self.outputs_list)
        self.export_selected_checkbox = QtWidgets.QCheckBox(export_Wizard)
        self.export_selected_checkbox.setObjectName("export_selected_checkbox")
        self.verticalLayout.addWidget(self.export_selected_checkbox)
        self.file_format_label = QtWidgets.QLabel(export_Wizard)
        self.file_format_label.setObjectName("file_format_label")
        self.verticalLayout.addWidget(self.file_format_label)
        self.file_format_combobox = QtWidgets.QComboBox(export_Wizard)
        self.file_format_combobox.setObjectName("file_format_combobox")
        self.verticalLayout.addWidget(self.file_format_combobox)
        self.pipeline_outputs_layout.addLayout(self.verticalLayout)
        self.asset_details_pipeline_layout.addLayout(self.pipeline_outputs_layout)
        self.main_layout.addLayout(self.asset_details_pipeline_layout)
        self.verticalLayout_2.addLayout(self.main_layout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.publish_button = QtWidgets.QPushButton(export_Wizard)
        self.publish_button.setObjectName("publish_button")
        self.horizontalLayout_4.addWidget(self.publish_button)
        self.cancel_Button = QtWidgets.QPushButton(export_Wizard)
        self.cancel_Button.setObjectName("cancel_Button")
        self.horizontalLayout_4.addWidget(self.cancel_Button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(export_Wizard)
        self.cancel_Button.clicked.connect(export_Wizard.reject)
        QtCore.QMetaObject.connectSlotsByName(export_Wizard)

    def retranslateUi(self, export_Wizard):
        _translate = QtCore.QCoreApplication.translate
        export_Wizard.setWindowTitle(_translate("export_Wizard", "Dialog"))
        self.outputs_label.setText(_translate("export_Wizard", "Outputs"))
        self.export_selected_checkbox.setText(_translate("export_Wizard", "Export Selected"))
        self.file_format_label.setText(_translate("export_Wizard", "File Format"))
        self.publish_button.setText(_translate("export_Wizard", "Publish"))
        self.cancel_Button.setText(_translate("export_Wizard", "Cancel"))
from .AssetDetailsView.assetDetailsView import AssetDetailsView
from .AssetListView.assetListView import AssetListView
from .PipelineViewerView.pipelineViewerView import PipelineViewerView
