# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assetDetails_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_asset_details(object):
    def setupUi(self, asset_details):
        asset_details.setObjectName("asset_details")
        asset_details.resize(407, 90)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(asset_details.sizePolicy().hasHeightForWidth())
        asset_details.setSizePolicy(sizePolicy)
        asset_details.setMinimumSize(QtCore.QSize(0, 90))
        self.formLayout = QtWidgets.QFormLayout(asset_details)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.name_d_label = QtWidgets.QLabel(asset_details)
        self.name_d_label.setObjectName("name_d_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_d_label)
        self.name_label = QtWidgets.QLabel(asset_details)
        self.name_label.setText("")
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_label)
        self.level_d_label = QtWidgets.QLabel(asset_details)
        self.level_d_label.setObjectName("level_d_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.level_d_label)
        self.level_label = QtWidgets.QLabel(asset_details)
        self.level_label.setText("")
        self.level_label.setObjectName("level_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.level_label)
        self.pipeline_d_label = QtWidgets.QLabel(asset_details)
        self.pipeline_d_label.setObjectName("pipeline_d_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pipeline_d_label)
        self.pipeline_label = QtWidgets.QLabel(asset_details)
        self.pipeline_label.setText("")
        self.pipeline_label.setObjectName("pipeline_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pipeline_label)
        self.tags_d_label = QtWidgets.QLabel(asset_details)
        self.tags_d_label.setObjectName("tags_d_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.tags_d_label)
        self.tags_label = QtWidgets.QLabel(asset_details)
        self.tags_label.setText("")
        self.tags_label.setObjectName("tags_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tags_label)
        self.comment_d_label = QtWidgets.QLabel(asset_details)
        self.comment_d_label.setObjectName("comment_d_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.comment_d_label)
        self.comment_label = QtWidgets.QLabel(asset_details)
        self.comment_label.setText("")
        self.comment_label.setObjectName("comment_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comment_label)

        self.retranslateUi(asset_details)
        QtCore.QMetaObject.connectSlotsByName(asset_details)

    def retranslateUi(self, asset_details):
        _translate = QtCore.QCoreApplication.translate
        asset_details.setWindowTitle(_translate("asset_details", "Form"))
        self.name_d_label.setText(_translate("asset_details", "Name:"))
        self.level_d_label.setText(_translate("asset_details", "Level:"))
        self.pipeline_d_label.setText(_translate("asset_details", "Pipeline:"))
        self.tags_d_label.setText(_translate("asset_details", "Tags:"))
        self.comment_d_label.setText(_translate("asset_details", "Comment:"))
