# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assetManager_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_asset_manager(object):
    def setupUi(self, asset_manager):
        asset_manager.setObjectName("asset_manager")
        asset_manager.resize(1035, 531)
        self.horizontalLayout = QtWidgets.QHBoxLayout(asset_manager)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.assets_label = QtWidgets.QLabel(asset_manager)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.assets_label.setFont(font)
        self.assets_label.setObjectName("assets_label")
        self.verticalLayout.addWidget(self.assets_label)
        self.asset_list = QtWidgets.QListWidget(asset_manager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asset_list.sizePolicy().hasHeightForWidth())
        self.asset_list.setSizePolicy(sizePolicy)
        self.asset_list.setMinimumSize(QtCore.QSize(256, 400))
        self.asset_list.setObjectName("asset_list")
        self.verticalLayout.addWidget(self.asset_list)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_asset_button = QtWidgets.QPushButton(asset_manager)
        self.add_asset_button.setObjectName("add_asset_button")
        self.horizontalLayout_2.addWidget(self.add_asset_button)
        self.remove_asset_button = QtWidgets.QPushButton(asset_manager)
        self.remove_asset_button.setObjectName("remove_asset_button")
        self.horizontalLayout_2.addWidget(self.remove_asset_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.retranslateUi(asset_manager)
        QtCore.QMetaObject.connectSlotsByName(asset_manager)

    def retranslateUi(self, asset_manager):
        _translate = QtCore.QCoreApplication.translate
        asset_manager.setWindowTitle(_translate("asset_manager", "Form"))
        self.assets_label.setText(_translate("asset_manager", "Assets"))
        self.add_asset_button.setText(_translate("asset_manager", "Add"))
        self.remove_asset_button.setText(_translate("asset_manager", "Remove"))
