# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asset_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_asset(object):
    def setupUi(self, asset):
        asset.setObjectName("asset")
        asset.resize(200, 20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(asset.sizePolicy().hasHeightForWidth())
        asset.setSizePolicy(sizePolicy)
        asset.setMinimumSize(QtCore.QSize(166, 20))
        self.horizontalLayout = QtWidgets.QHBoxLayout(asset)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_label = QtWidgets.QLabel(asset)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        self.line = QtWidgets.QFrame(asset)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.type_label = QtWidgets.QLabel(asset)
        self.type_label.setObjectName("type_label")
        self.horizontalLayout.addWidget(self.type_label)
        self.line_2 = QtWidgets.QFrame(asset)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.pipeline_step_label = QtWidgets.QLabel(asset)
        self.pipeline_step_label.setObjectName("pipeline_step_label")
        self.horizontalLayout.addWidget(self.pipeline_step_label)

        self.retranslateUi(asset)
        QtCore.QMetaObject.connectSlotsByName(asset)

    def retranslateUi(self, asset):
        _translate = QtCore.QCoreApplication.translate
        asset.setWindowTitle(_translate("asset", "Form"))
        self.name_label.setText(_translate("asset", "Asset_01"))
        self.type_label.setText(_translate("asset", "Model"))
        self.pipeline_step_label.setText(_translate("asset", "modeling"))
