# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainApplication_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1041, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setAutoFillBackground(False)
        self.tabs.setObjectName("tabs")
        self.assets_tab = QtWidgets.QWidget()
        self.assets_tab.setObjectName("assets_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.assets_tab)
        self.horizontalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabs.addTab(self.assets_tab, "")
        self.pipelines_tab = QtWidgets.QWidget()
        self.pipelines_tab.setEnabled(True)
        self.pipelines_tab.setObjectName("pipelines_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pipelines_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabs.addTab(self.pipelines_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabs.addTab(self.settings_tab, "")
        self.verticalLayout.addWidget(self.tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSet_as_current_project = QtWidgets.QAction(MainWindow)
        self.actionSet_as_current_project.setObjectName("actionSet_as_current_project")
        self.menuFile.addAction(self.actionSet_as_current_project)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabs.setTabText(self.tabs.indexOf(self.assets_tab), _translate("MainWindow", "Assets"))
        self.tabs.setTabText(self.tabs.indexOf(self.pipelines_tab), _translate("MainWindow", "Pipeline Configurator"))
        self.tabs.setTabText(self.tabs.indexOf(self.settings_tab), _translate("MainWindow", "Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSet_as_current_project.setText(_translate("MainWindow", "Set as current project"))
