# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainApplication_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.assetList_list = QtWidgets.QListWidget(self.centralwidget)
        self.assetList_list.setGeometry(QtCore.QRect(10, 50, 261, 371))
        self.assetList_list.setObjectName("assetList_list")
        self.assets_label = QtWidgets.QLabel(self.centralwidget)
        self.assets_label.setGeometry(QtCore.QRect(10, 20, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.assets_label.setFont(font)
        self.assets_label.setObjectName("assets_label")
        self.addAsset_button = QtWidgets.QPushButton(self.centralwidget)
        self.addAsset_button.setGeometry(QtCore.QRect(10, 440, 121, 31))
        self.addAsset_button.setObjectName("addAsset_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.assets_label.setText(_translate("MainWindow", "Assets"))
        self.addAsset_button.setText(_translate("MainWindow", "Add Asset"))
