# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pipeline_step_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pipeline_step(object):
    def setupUi(self, pipeline_step):
        pipeline_step.setObjectName("pipeline_step")
        pipeline_step.resize(150, 172)
        pipeline_step.setMinimumSize(QtCore.QSize(150, 110))
        self.verticalLayout = QtWidgets.QVBoxLayout(pipeline_step)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pipeline_step_label = QtWidgets.QLabel(pipeline_step)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pipeline_step_label.sizePolicy().hasHeightForWidth())
        self.pipeline_step_label.setSizePolicy(sizePolicy)
        self.pipeline_step_label.setMinimumSize(QtCore.QSize(0, 20))
        self.pipeline_step_label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pipeline_step_label.setFont(font)
        self.pipeline_step_label.setObjectName("pipeline_step_label")
        self.verticalLayout.addWidget(self.pipeline_step_label)
        self.program_label = QtWidgets.QLabel(pipeline_step)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.program_label.sizePolicy().hasHeightForWidth())
        self.program_label.setSizePolicy(sizePolicy)
        self.program_label.setMinimumSize(QtCore.QSize(0, 20))
        self.program_label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.program_label.setFont(font)
        self.program_label.setObjectName("program_label")
        self.verticalLayout.addWidget(self.program_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.inputs_label = QtWidgets.QLabel(pipeline_step)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputs_label.sizePolicy().hasHeightForWidth())
        self.inputs_label.setSizePolicy(sizePolicy)
        self.inputs_label.setObjectName("inputs_label")
        self.verticalLayout_2.addWidget(self.inputs_label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.outputs_label = QtWidgets.QLabel(pipeline_step)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputs_label.sizePolicy().hasHeightForWidth())
        self.outputs_label.setSizePolicy(sizePolicy)
        self.outputs_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputs_label.setObjectName("outputs_label")
        self.verticalLayout_3.addWidget(self.outputs_label)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(pipeline_step)
        QtCore.QMetaObject.connectSlotsByName(pipeline_step)

    def retranslateUi(self, pipeline_step):
        _translate = QtCore.QCoreApplication.translate
        pipeline_step.setWindowTitle(_translate("pipeline_step", "Form"))
        self.pipeline_step_label.setText(_translate("pipeline_step", "Pipeline Step"))
        self.program_label.setText(_translate("pipeline_step", "Program"))
        self.inputs_label.setText(_translate("pipeline_step", "Inputs"))
        self.outputs_label.setText(_translate("pipeline_step", "Outputs"))
