# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pipeline_step_output_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pipeline_step_output(object):
    def setupUi(self, pipeline_step_output):
        pipeline_step_output.setObjectName("pipeline_step_output")
        pipeline_step_output.resize(260, 27)
        self.horizontalLayout = QtWidgets.QHBoxLayout(pipeline_step_output)
        self.horizontalLayout.setContentsMargins(4, 2, 4, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.output_type_combobox = QtWidgets.QComboBox(pipeline_step_output)
        self.output_type_combobox.setObjectName("output_type_combobox")
        self.horizontalLayout.addWidget(self.output_type_combobox)
        self.output_name_lineedit = QtWidgets.QLineEdit(pipeline_step_output)
        self.output_name_lineedit.setObjectName("output_name_lineedit")
        self.horizontalLayout.addWidget(self.output_name_lineedit)
        self.remove_output_button = QtWidgets.QPushButton(pipeline_step_output)
        self.remove_output_button.setMaximumSize(QtCore.QSize(32, 16777215))
        self.remove_output_button.setObjectName("remove_output_button")
        self.horizontalLayout.addWidget(self.remove_output_button)

        self.retranslateUi(pipeline_step_output)
        QtCore.QMetaObject.connectSlotsByName(pipeline_step_output)

    def retranslateUi(self, pipeline_step_output):
        _translate = QtCore.QCoreApplication.translate
        pipeline_step_output.setWindowTitle(_translate("pipeline_step_output", "Form"))
        self.remove_output_button.setText(_translate("pipeline_step_output", "-"))
