# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pipeline_step_input_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pipeline_step_input(object):
    def setupUi(self, pipeline_step_input):
        pipeline_step_input.setObjectName("pipeline_step_input")
        pipeline_step_input.resize(200, 54)
        self.horizontalLayout = QtWidgets.QHBoxLayout(pipeline_step_input)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_type_combo_box = QtWidgets.QComboBox(pipeline_step_input)
        self.input_type_combo_box.setMinimumSize(QtCore.QSize(150, 0))
        self.input_type_combo_box.setObjectName("input_type_combo_box")
        self.verticalLayout.addWidget(self.input_type_combo_box)
        self.input_name_combobox = QtWidgets.QComboBox(pipeline_step_input)
        self.input_name_combobox.setMinimumSize(QtCore.QSize(150, 0))
        self.input_name_combobox.setObjectName("input_name_combobox")
        self.verticalLayout.addWidget(self.input_name_combobox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.remove_input_button = QtWidgets.QPushButton(pipeline_step_input)
        self.remove_input_button.setMaximumSize(QtCore.QSize(32, 16777215))
        self.remove_input_button.setObjectName("remove_input_button")
        self.horizontalLayout.addWidget(self.remove_input_button)

        self.retranslateUi(pipeline_step_input)
        QtCore.QMetaObject.connectSlotsByName(pipeline_step_input)

    def retranslateUi(self, pipeline_step_input):
        _translate = QtCore.QCoreApplication.translate
        pipeline_step_input.setWindowTitle(_translate("pipeline_step_input", "Form"))
        self.remove_input_button.setText(_translate("pipeline_step_input", "-"))
