# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadCurrentProjectWizard_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loadCurrentProjectWizard(object):
    def setupUi(self, loadCurrentProjectWizard):
        loadCurrentProjectWizard.setObjectName("loadCurrentProjectWizard")
        loadCurrentProjectWizard.resize(400, 60)
        self.verticalLayout = QtWidgets.QVBoxLayout(loadCurrentProjectWizard)
        self.verticalLayout.setObjectName("verticalLayout")
        self.load_project_label = QtWidgets.QLabel(loadCurrentProjectWizard)
        self.load_project_label.setObjectName("load_project_label")
        self.verticalLayout.addWidget(self.load_project_label)
        self.buttonBox = QtWidgets.QDialogButtonBox(loadCurrentProjectWizard)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(loadCurrentProjectWizard)
        self.buttonBox.accepted.connect(loadCurrentProjectWizard.accept)
        self.buttonBox.rejected.connect(loadCurrentProjectWizard.reject)
        QtCore.QMetaObject.connectSlotsByName(loadCurrentProjectWizard)

    def retranslateUi(self, loadCurrentProjectWizard):
        _translate = QtCore.QCoreApplication.translate
        loadCurrentProjectWizard.setWindowTitle(_translate("loadCurrentProjectWizard", "Dialog"))
        self.load_project_label.setText(_translate("loadCurrentProjectWizard", "Load project from settings?"))
