# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plugin_item_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plugin_item(object):
    def setupUi(self, plugin_item):
        plugin_item.setObjectName("plugin_item")
        plugin_item.resize(400, 23)
        self.horizontalLayout = QtWidgets.QHBoxLayout(plugin_item)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_label = QtWidgets.QLabel(plugin_item)
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.settings_button = QtWidgets.QPushButton(plugin_item)
        self.settings_button.setObjectName("settings_button")
        self.horizontalLayout.addWidget(self.settings_button)

        self.retranslateUi(plugin_item)
        QtCore.QMetaObject.connectSlotsByName(plugin_item)

    def retranslateUi(self, plugin_item):
        _translate = QtCore.QCoreApplication.translate
        plugin_item.setWindowTitle(_translate("plugin_item", "Form"))
        self.name_label.setText(_translate("plugin_item", "Plugin Name"))
        self.settings_button.setText(_translate("plugin_item", "Settings"))
