# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings(object):
    def setupUi(self, settings):
        settings.setObjectName("settings")
        settings.resize(494, 318)
        self.verticalLayout = QtWidgets.QVBoxLayout(settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.programs_label = QtWidgets.QLabel(settings)
        self.programs_label.setObjectName("programs_label")
        self.verticalLayout.addWidget(self.programs_label)
        self.programs_list = QtWidgets.QListWidget(settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.programs_list.sizePolicy().hasHeightForWidth())
        self.programs_list.setSizePolicy(sizePolicy)
        self.programs_list.setObjectName("programs_list")
        self.verticalLayout.addWidget(self.programs_list)
        self.plugins_label = QtWidgets.QLabel(settings)
        self.plugins_label.setObjectName("plugins_label")
        self.verticalLayout.addWidget(self.plugins_label)
        self.plugins_scrollbar = QtWidgets.QScrollArea(settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plugins_scrollbar.sizePolicy().hasHeightForWidth())
        self.plugins_scrollbar.setSizePolicy(sizePolicy)
        self.plugins_scrollbar.setMinimumSize(QtCore.QSize(0, 130))
        self.plugins_scrollbar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plugins_scrollbar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plugins_scrollbar.setWidgetResizable(True)
        self.plugins_scrollbar.setObjectName("plugins_scrollbar")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 461, 128))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.plugins_scrollbar.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.plugins_scrollbar)

        self.retranslateUi(settings)
        QtCore.QMetaObject.connectSlotsByName(settings)

    def retranslateUi(self, settings):
        _translate = QtCore.QCoreApplication.translate
        settings.setWindowTitle(_translate("settings", "Form"))
        self.programs_label.setText(_translate("settings", "Programs"))
        self.plugins_label.setText(_translate("settings", "Plugins"))
