# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pipeline_step_settings_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pipeline_step_settings_GUI(object):
    def setupUi(self, pipeline_step_settings_GUI):
        pipeline_step_settings_GUI.setObjectName("pipeline_step_settings_GUI")
        pipeline_step_settings_GUI.resize(400, 20)
        self.horizontalLayout = QtWidgets.QHBoxLayout(pipeline_step_settings_GUI)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.configs_combobox = QtWidgets.QComboBox(pipeline_step_settings_GUI)
        self.configs_combobox.setObjectName("configs_combobox")
        self.horizontalLayout.addWidget(self.configs_combobox)

        self.retranslateUi(pipeline_step_settings_GUI)
        QtCore.QMetaObject.connectSlotsByName(pipeline_step_settings_GUI)

    def retranslateUi(self, pipeline_step_settings_GUI):
        _translate = QtCore.QCoreApplication.translate
        pipeline_step_settings_GUI.setWindowTitle(_translate("pipeline_step_settings_GUI", "Form"))
