# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pipelineStepViewer_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pipeline_step_viewer(object):
    def setupUi(self, pipeline_step_viewer):
        pipeline_step_viewer.setObjectName("pipeline_step_viewer")
        pipeline_step_viewer.resize(326, 300)
        pipeline_step_viewer.setFocusPolicy(QtCore.Qt.StrongFocus)
        pipeline_step_viewer.setAutoFillBackground(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(pipeline_step_viewer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(pipeline_step_viewer)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(10)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        self.name_label.setObjectName("name_label")
        self.verticalLayout_2.addWidget(self.name_label)
        self.program_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.program_label.sizePolicy().hasHeightForWidth())
        self.program_label.setSizePolicy(sizePolicy)
        self.program_label.setObjectName("program_label")
        self.verticalLayout_2.addWidget(self.program_label)
        self.state_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.state_label.sizePolicy().hasHeightForWidth())
        self.state_label.setSizePolicy(sizePolicy)
        self.state_label.setObjectName("state_label")
        self.verticalLayout_2.addWidget(self.state_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(pipeline_step_viewer)
        QtCore.QMetaObject.connectSlotsByName(pipeline_step_viewer)

    def retranslateUi(self, pipeline_step_viewer):
        _translate = QtCore.QCoreApplication.translate
        pipeline_step_viewer.setWindowTitle(_translate("pipeline_step_viewer", "Form"))
        self.name_label.setText(_translate("pipeline_step_viewer", "Step Name"))
        self.program_label.setText(_translate("pipeline_step_viewer", "Program"))
        self.state_label.setText(_translate("pipeline_step_viewer", "State"))
