# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pipelineViewer_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pipeline_viewer(object):
    def setupUi(self, pipeline_viewer):
        pipeline_viewer.setObjectName("pipeline_viewer")
        pipeline_viewer.resize(400, 212)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pipeline_viewer.sizePolicy().hasHeightForWidth())
        pipeline_viewer.setSizePolicy(sizePolicy)
        pipeline_viewer.setMinimumSize(QtCore.QSize(200, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(pipeline_viewer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pipeline_label = QtWidgets.QLabel(pipeline_viewer)
        self.pipeline_label.setObjectName("pipeline_label")
        self.verticalLayout.addWidget(self.pipeline_label)
        self.pipeline_scrollbar = QtWidgets.QScrollArea(pipeline_viewer)
        self.pipeline_scrollbar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.pipeline_scrollbar.setWidgetResizable(True)
        self.pipeline_scrollbar.setObjectName("pipeline_scrollbar")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 398, 177))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.pipeline_scrollbar.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.pipeline_scrollbar)

        self.retranslateUi(pipeline_viewer)
        QtCore.QMetaObject.connectSlotsByName(pipeline_viewer)

    def retranslateUi(self, pipeline_viewer):
        _translate = QtCore.QCoreApplication.translate
        pipeline_viewer.setWindowTitle(_translate("pipeline_viewer", "Form"))
        self.pipeline_label.setText(_translate("pipeline_viewer", "Pipeline"))
