# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tagDatabase_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tagDatabase(object):
    def setupUi(self, tagDatabase):
        tagDatabase.setObjectName("tagDatabase")
        tagDatabase.resize(478, 300)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(tagDatabase)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tag_list = QtWidgets.QListWidget(tagDatabase)
        self.tag_list.setObjectName("tag_list")
        self.horizontalLayout_2.addWidget(self.tag_list)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_tag_button = QtWidgets.QPushButton(tagDatabase)
        self.add_tag_button.setObjectName("add_tag_button")
        self.verticalLayout.addWidget(self.add_tag_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)

        self.retranslateUi(tagDatabase)
        QtCore.QMetaObject.connectSlotsByName(tagDatabase)

    def retranslateUi(self, tagDatabase):
        _translate = QtCore.QCoreApplication.translate
        tagDatabase.setWindowTitle(_translate("tagDatabase", "Form"))
        self.add_tag_button.setText(_translate("tagDatabase", "Add Tag"))
